# Generated by Django 5.2.7 on 2025-10-19 06:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('BARISTA', 'Barista'), ('ADMIN', 'Admin')], default='CUSTOMER', help_text='User role determines access permissions', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Phone number for order notifications', max_length=20, null=True)),
                ('loyalty_points', models.IntegerField(default=0, help_text='Accumulated loyalty points from purchases', validators=[django.core.validators.MinValueValidator(0)])),
                ('push_token', models.CharField(blank=True, help_text='Device push notification token for mobile alerts', max_length=255, null=True)),
                ('notification_enabled', models.BooleanField(default=True, help_text='Whether user wants to receive push notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer name displayed to customers', max_length=200)),
                ('description', models.TextField(help_text='What customer gets with this offer')),
                ('points_required', models.IntegerField(help_text='Points needed to redeem this offer', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether offer is currently available')),
                ('valid_from', models.DateTimeField(help_text='When offer becomes available')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When offer expires (null = never expires)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_required'],
                'indexes': [models.Index(fields=['is_active', 'valid_from'], name='api_loyalty_is_acti_9ad0ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name of the menu item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item')),
                ('image', models.ImageField(blank=True, help_text='Product image displayed in app', null=True, upload_to='menu_items/')),
                ('item_type', models.CharField(choices=[('COFFEE', 'Coffee'), ('DESSERT', 'Dessert')], help_text='Category: coffee or dessert', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price in dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True, help_text='Whether item is currently available for ordering')),
                ('preparation_time', models.IntegerField(default=5, help_text='Estimated preparation time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When item was added to menu')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time item details were updated')),
            ],
            options={
                'ordering': ['item_type', 'title'],
                'indexes': [models.Index(fields=['item_type', 'is_available'], name='api_menuite_item_ty_67adc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECEIVED', help_text='Current status of the order', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total order cost including all items', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Special instructions from customer')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Future time when order should be prepared', null=True)),
                ('is_favourite', models.BooleanField(default=False, help_text='Whether customer saved this as favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When order was placed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was completed/picked up', null=True)),
                ('customer', models.ForeignKey(help_text='Customer who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_RECEIVED', 'Order Received'), ('ORDER_PREPARING', 'Order Preparing'), ('ORDER_READY', 'Order Ready'), ('ORDER_COMPLETED', 'Order Completed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PROMOTION', 'Promotional')], help_text='Category of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification headline', max_length=200)),
                ('message', models.TextField(help_text='Notification body text')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has seen notification')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When notification was sent')),
                ('user', models.ForeignKey(help_text='User who received notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Related order if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.order')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name for this saved order", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When template was saved')),
                ('customer', models.ForeignKey(help_text='Customer who saved this template', on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('template_order', models.ForeignKey(help_text='Order that serves as template', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of this item in order', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of order (captures menu item price)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('customizations', models.TextField(blank=True, help_text='Custom modifications to this item')),
                ('menu_item', models.ForeignKey(help_text='Menu item being ordered', on_delete=django.db.models.deletion.CASCADE, to='api.menuitem')),
                ('order', models.ForeignKey(help_text='Parent order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_9b9076_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='api_user_email_a7eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='api_order_custome_44d87a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='api_order_status_1d49fe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['scheduled_for'], name='api_order_schedul_352e67_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-sent_at'], name='api_notific_user_id_2861b5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'),
        ),
        migrations.AddIndex(
            model_name='favouriteorder',
            index=models.Index(fields=['customer', '-created_at'], name='api_favouri_custome_a02e5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favouriteorder',
            unique_together={('customer', 'name')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='api_orderit_order_i_3f9c70_idx'),
        ),
    ]
