# Generated by Django 5.2.7 on 2025-10-20 00:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(help_text='Points deducted at redemption time', validators=[django.core.validators.MinValueValidator(1)])),
                ('redemption_code', models.CharField(help_text='Unique code for barista verification', max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether redemption has been applied to an order')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, help_text='When offer was redeemed')),
                ('customer', models.ForeignKey(help_text='Customer who redeemed the offer', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_redemptions', to=settings.AUTH_USER_MODEL)),
                ('loyalty_offer', models.ForeignKey(help_text='Loyalty offer that was redeemed', on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.loyaltyoffer')),
                ('order', models.ForeignKey(blank=True, help_text='Order where redemption was applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='api.order')),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['customer', '-redeemed_at'], name='api_loyalty_custome_2435d6_idx'), models.Index(fields=['redemption_code'], name='api_loyalty_redempt_647750_idx'), models.Index(fields=['is_used'], name='api_loyalty_is_used_e062c9_idx')],
            },
        ),
    ]
